name: .NET Core

on:
  pull_request:
    branches: [ master ]

jobs:
  hyperaishell_foundation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: |
        dotnet restore HyperaiShell.Foundation
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore HyperaiShell.Foundation
    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: HyperaiShell.Foundation/HyperaiShell.Foundation.csproj
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{ secrets.PACKAGE_PUSH }}
        INCLUDE_SYMBOLS: true